deploy: stabilize database preparation in docker-entrypoint

diff --git a/smart-quote-api/bin/docker-entrypoint b/smart-quote-api/bin/docker-entrypoint
--- a/smart-quote-api/bin/docker-entrypoint
+++ b/smart-quote-api/bin/docker-entrypoint
@@ -8,7 +8,8 @@ fi
 
 # If running the rails server then create or migrate existing database
 if [ "${@: -2:1}" == "./bin/rails" ] && [ "${@: -1:1}" == "server" ]; then
-  ./bin/rails db:prepare
+  echo "Preparing database..."
+  ./bin/rails db:prepare || echo "Database prepare failed, moving to migrate..."
   ./bin/rails db:migrate
 fi
 
